#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#welcome:
#   path: /welcome
#   controller: App\Controller\WelcomeController::index

#login:
#   path: /login
#   controller: App\Controller\SecurityController::login

